<?php require_once 'templates/tareas/header.phtml'; ?>

<div class="container mt-1">
    <h5>Agregar persona</h5>
    <form action="agregarPersona" method="POST">
        <div class="mb-1">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre" required>
        </div>
        <div class="mb-1">
            <label for="apellido" class="form-label">Apellido</label>
            <input type="text" class="form-control" id="apellido" name="apellido" required>
        </div>
        <div class="mb-1">
            <label for="diaDeNacimiento" class="form-label">Día de nacimiento</label>
            <input type="number" class="form-control" id="diaDeNacimiento" name="diaDeNacimiento" required>
        </div>
        <div class="mb-1">
            <label for="mesDeNacimiento" class="form-label">Mes de nacimiento</label>
            <input type="number" class="form-control" id="mesDeNacimiento" name="mesDeNacimiento" required>
        </div>
        <div class="mb-1">
            <label for="anioDeNacimiento" class="form-label">Año de nacimiento</label>
            <input type="number" class="form-control" id="anioDeNacimiento" name="anioDeNacimiento" required>
        </div>
        <div class="mb-1">
            <label for="horaDeNacimiento" class="form-label">Hora de nacimiento</label>
            <input type="number" class="form-control" id="horaDeNacimiento" name="horaDeNacimiento" required>
        </div>
        <div class="mb-1">
            <label for="imgPersona" class="form-label">Imagen</label>
            <input type="text" class="form-control" id="imgPersona" name="imgPersona">
        </div>
        <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
    </form>
</div>

<?php require_once 'templates/tareas/footer.phtml'; ?>
