<?php
require 'templates/tareas/header.phtml';   
?>
<div class="container">
    <div class="row">
        <?php foreach($persona as $item) { ?>      
            <div class="col-md-3"> <!-- Ajusta el número de columnas según lo que necesites -->
                <div class="card mb-3">
                    <img src="<?php echo $item->imgPersona; ?>" class="card-img-top"?>
                    <div class="card-body">
                    <h5 class="card-title"><?php echo $item->nombre . ' ' . $item->apellido; ?></h5>

                        <p class="card-text">
                            <strong>Dia de nacimiento:</strong> <?php echo $item->diaNacimiento;?><br>
                            <strong>Mes de nacimiento:</strong> <?php echo $item->mesNacimiento;?><br>
                            <strong>Año de nacimiento:</strong> <?php echo $item->anioNacimiento;?><br>
                        </p>
                        
                        <a href="personaId/<?php echo $item->id; ?>" class="btn btn-primary">Ver persona</a>
                        <?php if (Autorizacion::esAdministrador()) { ?>
                        <a href="eliminarPersona/<?php echo $item->id; ?>" class="btn btn-danger">Eliminar</a>
                        <a href="actualizarPersona/<?php echo $item->id; ?>" class="btn btn-success">Modificar</a>
                        <?php } ?>
                    </div>
                </div>
            </div>      
        <?php } ?>
    </div>
</div>
<?php
require './templates/tareas/footer.phtml'; 
?>
