<?php require './templates/tareas/header.phtml'; ?>

<div class="container mt-5">
    <?php foreach ($lista as $persona) { ?>
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-4">
                <img src="<?= $persona->imgHoroscopos; ?>" class="img-fluid rounded-start" alt="Imagen del Producto">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><?= $persona->elemento; ?></h5>
                        <p class="card-text"><?= $persona->caracteristicasGenerales; ?></p>
                        <p class="card-text"><?= $persona->predicciones; ?></p>
                        
                        <a href="lista" class="btn btn-primary">Volver</a>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
</div>

<?php require_once 'templates/tareas/footer.phtml'; ?>