<?php
require './templates/tareas/header.phtml';   
?>
<div class="container mt-4">
    <div class="row">
        <?php foreach($signo as $sig) { ?>      
            <div class="col-md-4 mb-4"> 
                <div class="card">
                <img src="<?= htmlspecialchars($sig->imgHoroscopos); ?>" class="card-img-top" alt="<?= htmlspecialchars($sig->id_signo); ?>">

                    <div class="card-body">
                        <h5 class="card-title"><?= htmlspecialchars($sig->id_signo); ?></h5>
                        <p class="card-text">
                            <strong>elemento:</strong> <?= htmlspecialchars($sig->elemento); ?><br>
                            <strong>caracteristicas:</strong> <?= htmlspecialchars($sig->caracteristicasGenerales); ?><br>
                            <strong>predicciones:</strong> <?= htmlspecialchars($sig->predicciones); ?>
                        </p>
                        <a href="signoId/<?= $sig->id_signo; ?>" class="btn btn-primary">Ver Productos</a>
                        <?php if (Autorizacion::esAdministrador()) { ?>
                            <a href="eliminarSigno/<?= $sig->id_signo; ?>" class="btn btn-danger">Eliminar</a>
                            <a href="formularioSignoModificacion/<?= $sig->id_signo; ?>" class="btn btn-success">Modificar</a>
                        <?php } ?>
                    </div>
                </div>
            </div>      
        <?php } ?>
    </div>
</div>
<?php
require_once 'templates/tareas/footer.phtml';
?>
